version: "3.1"
services:
  frontend-app:
    container_name: frontend-app
    image: frontend
    build: ./frontend/
    ports:
      - "8080:8080"
    command: 'npm run serve'
  db:
    container_name: db_auth_2
    image: postgres:14.3-alpine
    volumes:
      - "./backend/src/main/resources:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db