version: '3.5'

services:
  db:
    container_name: db_auth_2
    image: postgres:14.3-alpine
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db