version: '3.5'

services:
  db:
    container_name: db_auth
    image: postgres:14.3-alpine
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"